Chilakala Jaya Karthik
**20BCD7013**


---


jayakarthik.20bcd7013@vitap.ac.in


---


VIT AP



In [52]:
#Assign your Name to variable name and Age to variable age. Make a Python program that 
#prints your name and age.
name="karthik"
age=21
print(name,age)

karthik 21


In [53]:
#X="Datascience is used to extract meaningful insights."
#Split the string
X="Datascience is used to extract meaningful insights."
X=X.split()
print(X)

['Datascience', 'is', 'used', 'to', 'extract', 'meaningful', 'insights.']


In [54]:
#Make a function that gives multiplication of two numbers
def fun(a,b):
    return a*b
fun(4,56)

224

In [55]:
#Create a Dictionary of 5 States with their capitals. also print the keys and values
capitals = { "Maharashtra": "Mumbai",
             "Delhi" : "New Delhi",
             "Uttar pradesh":"Lucknow",
             "Tamil Nadu ": "Chennai",
           "Punjab":"Chandigarh"}
print(capitals)

{'Maharashtra': 'Mumbai', 'Delhi': 'New Delhi', 'Uttar pradesh': 'Lucknow', 'Tamil Nadu ': 'Chennai', 'Punjab': 'Chandigarh'}


In [56]:
#Create a list of 1000 numbers using range function
x=list(range(1,1001))
print(x)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 22

In [57]:
#Create an identity matrix of dimension 4 by 4
import numpy as np

dimension = 4
id_mat = np.identity(dimension, dtype="int")
print(id_mat)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [58]:
#Create a 3x3 matrix with values ranging from 1 to 9
m =  np.arange(1, 10).reshape(3,3)
print(m)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [59]:
#Create 2 similar dimensional array and perform sum on them.
m1 =  np.arange(1, 10).reshape(3,3)
m2 =  np.arange(10, 19).reshape(3,3)
s=m1+m2
print(s)

[[11 13 15]
 [17 19 21]
 [23 25 27]]


In [60]:
#Generate the series of dates from 1st Feb, 2023 to 1st March, 2023 (both inclusive)
from datetime import datetime
import pandas as pd
start=datetime.strptime("2023-02-01", "%Y-%m-%d")
end=datetime.strptime("2023-03-01", "%Y-%m-%d")
date_list = pd.date_range(start, end, freq='D')
print(f"Creating list of dates starting from {start} to {end}")
print(date_list)

Creating list of dates starting from 2023-02-01 00:00:00 to 2023-03-01 00:00:00
DatetimeIndex(['2023-02-01', '2023-02-02', '2023-02-03', '2023-02-04',
               '2023-02-05', '2023-02-06', '2023-02-07', '2023-02-08',
               '2023-02-09', '2023-02-10', '2023-02-11', '2023-02-12',
               '2023-02-13', '2023-02-14', '2023-02-15', '2023-02-16',
               '2023-02-17', '2023-02-18', '2023-02-19', '2023-02-20',
               '2023-02-21', '2023-02-22', '2023-02-23', '2023-02-24',
               '2023-02-25', '2023-02-26', '2023-02-27', '2023-02-28',
               '2023-03-01'],
              dtype='datetime64[ns]', freq='D')


In [61]:
#Given a dictionary, convert it into corresponding dataframe and display it
#dictionary = {'Brand': ['Maruti', 'Renault', 'Hyndai'], 'Sales' : [250, 200, 240]}
import pandas as pd
dictionary = {'Brand': ['Maruti', 'Renault', 'Hyndai'], 'Sales' : [250, 200, 240]}
dic=pd.DataFrame.from_dict(dictionary)
print(dic)

     Brand  Sales
0   Maruti    250
1  Renault    200
2   Hyndai    240
